sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n test-env python=$PYTHON_VERSION nose
  - source activate test-env
  - pip install https://github.com/qiime2/qiime2/archive/master.zip
  # pip has a much newer version of flake8 than conda.
  - pip install flake8
  - pip install .
script:
  - QIIMETEST= nosetests
  - flake8
  - source tab-qiime
